service: neural-captcha-buster

frameworkVersion: ">=1.38.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  readCaptcha:
    handler: http_handler.read
    events:
      - http:
          path: captcha/read
          method: post
